[package]
authors = ["Joseph Lai"]
description = "The tree command, but better"
edition = "2021"
keywords = ["tree"]
name = "oak"
version = "0.1.0"

[dependencies]
ansi_term = "0.12.1"
bat = "0.18.3"
crossterm = "0.22.1"
ignore = "0.4.18"
structopt = "0.3.25"
tui = { version = "0.16.0", default-features = false, features = ["crossterm"] }

