# ===============
# Configure nomad
# ===============


# ================================= INFO START =================================

# Refer to the repository's README to learn more about how to use nomad:
#
#     https://github.com/JosephLai241/nomad

# If you are unfamiliar with TOML, refer to the official site to learn more about
# its syntax:
#
#     https://toml.io/en/

# ------------------------------- CUSTOM COLORS --------------------------------

# If you do not want to use the default colors, you can set the color to an Xterm
# 256 color's hex code located here:
#
#    https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
#
# For example, if you want to set something to the color d78700 (a shade of orange),
# wrap the value in quotes, ie. "d78700".

# ------------------------------------------------------------------------------

# ================================== INFO END ==================================

# NOTE
# ----
#
# The default values for each item are displayed below.
# The default value will be used if an invalid value is provided.


#
# Uncomment the items below this table to set the tree's style.
#
[tree]
#indent = 4
#padding = 1


#
# Uncomment the item below this table to set tree item colors.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "green"
#    * "purple"
#    * "red"
#    * "white"
#    * "yellow"
#
[tree.items.colors]
#directory_color = "blue"


#
# Uncomment the items below this table to set the tree's indent characters.
#
[tree.indent_chars]
#down = "|"
#down_and_right = "├"
#empty = " "
#right = "─"
#turn_right = "└"


#
# Uncomment the items below this table to set label styles.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "green"
#    * "purple"
#    * "red"
#    * "white"
#    * "yellow"
#
[tree.labels]
#item_labels = "d78700"
#directory_labels = "d78700"


#
# Uncomment the items below this table to set the text displayed for each Git
# item's status.
#
[tree.git.markers]
#conflicted_marker = "!"
#deleted_marker = "D"
#modified_marker = "M"
#renamed_marker = "R"
#untracked_marker = "U"

#staged_added_marker = "SA"
#staged_deleted_marker = "SD"
#staged_modified_marker = "SM"
#staged_renamed_marker = "SR"


#
# Uncomment the items below this table to set the colors of the Git markers.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "green"
#    * "purple"
#    * "red"
#    * "white"
#    * "yellow"
#
[tree.git.colors]
#conflicted_color = "red"
#deleted_color = "red"
#modified_color = "d78700"          # A shade of orange.
#renamed_color = "red"
#untracked_color = "767676"         # A shade of gray.

#staged_added_color = "green"
#staged_deleted_color = "red"
#staged_modified_color = "d78700"   # A shade of orange.
#staged_renamed_color = "red"


#
# Uncomment the item below this table to set the color of the text that is
# matched by the pattern flag (`-p/--pattern`).
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "green"
#    * "purple"
#    * "red"
#    * "white"
#    * "yellow"
#
[tree.regex]
#match_color = "0087ff"    # A shade of blue.


#
# Uncomment the items below this table to set the TUI's colors.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "darkgray"
#    * "gray"
#    * "green"
#    * "lightblue"
#    * "lightcyan"
#    * "lightgreen"
#    * "lightmagenta"
#    * "lightred"
#    * "lightyellow"
#    * "magenta"
#    * "red"
#    * "white"
#    * "yellow"
#
[tui.style]
#border_color = "0087ff"    # A shade of blue.

# The color of the tree item if it does not contain any Git changes.
#standard_item_highlight_color = "0087ff"    # A shade of blue.


#
# Uncomment the items below this table to set the Git colors in the TUI.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "darkgray"
#    * "gray"
#    * "green"
#    * "lightblue"
#    * "lightcyan"
#    * "lightgreen"
#    * "lightmagenta"
#    * "lightred"
#    * "lightyellow"
#    * "magenta"
#    * "red"
#    * "white"
#    * "yellow"
#
[tui.git.colors]
#conflicted_color = "red"
#deleted_color = "red"
#modified_color = "d78700"          # A shade of orange.
#renamed_color = "red"
#untracked_color = "767676"         # A shade of gray.

#staged_added_color = "green"
#staged_deleted_color = "red"
#staged_modified_color = "d78700"   # A shade of orange.
#staged_renamed_color = "red"


#
# Uncomment the item below this table to set the color of the text that is
# matched when searching for a pattern in the text view.
#
# Default colors
# --------------
#    * "black"
#    * "blue"
#    * "cyan"
#    * "darkgray"
#    * "gray"
#    * "green"
#    * "lightblue"
#    * "lightcyan"
#    * "lightgreen"
#    * "lightmagenta"
#    * "lightred"
#    * "lightyellow"
#    * "magenta"
#    * "red"
#    * "white"
#    * "yellow"
#
[tui.regex]
#match_color = "0087ff"    # A shade of blue.


