# ===============
# Configure nomad
# ===============


# ================================= INFO START =================================

# Refer to the repository's README to learn more about how to use nomad:
#
#     https://github.com/JosephLai241/nomad

# If you are unfamiliar with TOML, refer to the official site to learn more about
# its syntax:
#
#     https://toml.io/en/

# ----------------------------------- COLORS -----------------------------------

# These are the default colors:
#    * "black"
#    * "blue"
#    * "cyan"
#    * "green"
#    * "purple"
#    * "red"
#    * "white"
#    * "yellow"

# If you do not want to use the default colors, you can set the color to an Xterm
# 256 color's hex code located here:
#
#    https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg
#
# For example, if you want to set something to the color d78700 (a shade of orange),
# wrap the value in quotes, ie. "d78700".

# ================================== INFO END ==================================

# The default values for each item are displayed below.


#
# Uncomment the items below this table to set the text displayed for each Git
# item's status.
#
[git.markers]
#conflicted_marker = "CONFLICT"
#deleted_marker = "D"
#modified_marker = "M"
#renamed_marker = "R"
#untracked_marker = "U"

#staged_added_marker = "SA"
#staged_deleted_marker = "SD"
#staged_modified_marker = "SM"
#staged_renamed_marker = "SR"


#
# Uncomment the items below this table to set the colors of the Git markers.
#
[git.colors]
#conflicted_color = "red"
#deleted_color = "red"
#modified_color = "d78700"          # A shade of orange.
#renamed_color = "red"
#untracked_color = "767676"         # A shade of gray.

#staged_added_color = "green"
#staged_deleted_color = "red"
#staged_modified_color = "d78700"   # A shade of orange.
#staged_renamed_color = "red"


#
# Uncomment the item below this table to set the color of the text that is
# matched by the pattern flag (`-p/--pattern`).
#
[regex]
#match_color = "0087ff"             # A shade of blue.


